workflows:
  android-build:
    name: Android LSPosed Hook Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Set up Java
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
      - name: Extract project files
        script: |
          unzip -o LSPosedHookModule_Final.zip -d .
      - name: Grant execute permission for Gradle
        script: |
          chmod +x ./LSPosedHookModule_Final/gradlew
      - name: Build debug APK
        script: |
          cd LSPosedHookModule_Final
          ./gradlew assembleDebug
    artifacts:
      - LSPosedHookModule_Final/app/build/outputs/apk/debug/app-debug.apk
